# Generated by Django 3.1.5 on 2021-01-23 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass_name', models.CharField(max_length=50)),
                ('mass_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=50)),
                ('member_phone_no', models.CharField(blank=True, default='-', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='This_Sunday_Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_phone_no', models.CharField(max_length=12)),
                ('mass_attended', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.mass')),
                ('member_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.town')),
                ('member_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attendance.member')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='member_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.town'),
        ),
    ]
